In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB # for hamdling descrete values

In [2]:
data=pd.read_csv('spam.csv')

In [3]:
data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
data.shape

(5572, 2)

In [5]:
data['spam']= data.Category.apply(lambda x: 1 if x=='spam' else 0)

In [6]:
data.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
data.drop('Category', axis=1)
data.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
x= data.Message
y= data.spam

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25, random_state=37)

In [10]:
x_train.shape

(4179,)

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
cv=CountVectorizer()  # its a class ..so object is created here
x_train_counter = cv.fit_transform(x_train.values)

In [13]:
cv.get_feature_names()

C:\Users\palla\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808726822',
 '07815296484',
 '07821230901',
 '07880867867',
 '0789xxxxxxx',
 '07946746291',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '083',
 '0844',
 '08448350055',
 '0845',
 '08450542832',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700435505150p',
 '08700469649',
 '08700621170150p',
 '08701417012',
 '08701417012150p',
 '087016248',
 '08701752560',
 '087018728737',
 '0870241182716',
 '08702490080',
 '08702840625',
 '08704050406',
 '08704439680',
 '08706091795',
 '08707509020',
 '0870753331018',
 '08707808226',
 '08708034412',
 '08708800282',
 '08709222922',
 '08709501522',
 '0871',
 '087104711148',
 '08712101358',
 '0871212025016',
 '08712300220',
 '087123002209am',
 '08712317606',
 '08712400602450p',
 '08712402050',
 '08712402902',
 '08712404000',
 '08712405020',
 '08712405022',
 '08712460324',
 '08712466669',
 '0871277810710p',
 '0871277810810',
 '08714342399',
 '08714712379',
 '08714712388',
 '08714712412',
 '08714714011',
 '08715203652',
 '08715203677',
 '08715203685',
 '08715205273',
 '08715705022',
 '08717111821',
 '0871750',
 '08717507382',
 '08717509990',
 '08717890890',
 '08717895698',
 '08717898035',
 '08718720201',
 '08718723815',
 '087187262701',
 '08718726970',
 '08718726978',
 '087187272008',
 '08718727870',
 '08718730555',
 '08718730666',
 '08718738001',
 '08718738002',
 '08718738034',
 '08719180248',
 '08719181503',
 '08719181513',
 '08719899230',
 '09',
 '09041940223',
 '09050000301',
 '09050000332',
 '09050000460',
 '09050000878',
 '09050000928',
 '09050001295',
 '09050003091',
 '09050005321',
 '09050090044',
 '09050280520',
 '09056242159',
 '09057039994',
 '09058094454',
 '09058094507',
 '09058094565',
 '09058094583',
 '09058094594',
 '09058094597',
 '09058094599',
 '09058095107',
 '09058097189',
 '09058097218',
 '09058098002',
 '09058099801',
 '09061104276',
 '09061104283',
 '09061209465',
 '09061213237',
 '09061221061',
 '09061221066',
 '09061701444',
 '09061701461',
 '09061701851',
 '09061701939',
 '09061702893',
 '09061743386',
 '09061743806',
 '09061743811',
 '09061744553',
 '09061790121',
 '09061790125',
 '09061790126',
 '09063440451',
 '09063442151',
 '09063458130',
 '0906346330',
 '09064011000',
 '09064012103',
 '09064012160',
 '09064015307',
 '09064017295',
 '09064017305',
 '09064019014',
 '09065069154',
 '09065171142',
 '09065174042',
 '09065394514',
 '09065394973',
 '09065989180',
 '09065989182',
 '09066350750',
 '09066358152',
 '09066358361',
 '09066361921',
 '09066362206',
 '09066362220',
 '09066362231',
 '09066364311',
 '09066364349',
 '09066364589',
 '09066368753',
 '09066380611',
 '09066382422',
 '09066612661',
 '09066660100',
 '09071512433',
 '09071517866',
 '09077818151',
 '09090900040',
 '09094100151',
 '09094646631',
 '09094646899',
 '09095350301',
 '09096102316',
 '09099725823',
 '09099726395',
 '09099726429',
 '09099726553',
 '09111030116',
 '09111032124',
 '0a',
 '0quit',
 '10',
 '100',
 '1000',
 '1000s',
 '100percent',
 '100txt',
 '1030',
 '10am',
 '10k',
 '10p',
 '10ppm',
 '11',
 '1120',
 '113',
 '114',
 '1146',
 '118p',
 '11mths',
 '11pm',
 '12',
 '1205',
 '121',
 '1225',
 '125',
 '1250',
 '125gift',
 '128',
 '12hours',
 '12hrs',
 '12mths',
 '13',
 '130',
 '1327',
 '139',
 '14',
 '140',
 '1405',
 '145',
 '146tf150p',
 '14tcr',
 '14thmarch',
 '15',
 '150',
 '1500',
 '150p',
 '150pm',
 '150ppermesssubscription',
 '150ppm',
 '150ppmpobox10183bhamb64xe',
 '150ppmsg',
 '150pw',
 '153',
 '15pm',
 '16',
 '1680',
 '169',
 '177',
 '18',
 '180',
 '1843',
 '18p',
 '18yrs',
 '1956669',
 '1apple',
 '1b6a5ecef91ff9',
 '1cup',
 '1da',
 '1er',
 '1hr',
 '1lemon',
 '1million',
 '1pm',
 '1st',
 '1st4terms',
 '1stchoice',
 '1stone',
 '1thing',
 '1tulsi',
 '1win150ppmx3',
 '1winaweek',
 '1winawk',
 '1x150p',
 '20',
 '200',
 '2000',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '200p',
 '2025050',
 '20m12aq',
 '20p',
 '21',
 '21870000',
 '21st',
 '22',
 '220',
 '220cm2',
 '2309',
 '23f',
 '23g',
 '24',
 '24m',
 '25',
 '250',
 '250k',
 '255',
 '25p',
 '26',
 '2667',
 '27',
 '28',
 '2814032',
 '28days',
 '28th',
 '28thfeb',
 '29',
 '2b',
 '2bold',
 '2c',
 '2day',
 '2docd',
 '2end',
 '2ez',
 '2find',
 '2getha',
 '2geva',
 '2go',
 '2gthr',
 '2hook',
 '2hrs',
 '2i',
 '2lands',
 '2marrow',
 '2moro',
 '2morow',
 '2morrow',
 '2morrowxxxx',
 '2mwen',
 '2nd',
 '2nhite',
 '2nite',
 '2optout',
 '2p',
 '2price',
 '2px',
 '2rcv',
 '2stop',
 '2stoptxt',
 '2u',
 '2watershd',
 '2wks',
 '2wt',
 '2wu',
 '2years',
 '2yr',
 '30',
 '300',
 '300603',
 '300p',
 '3030',
 '30ish',
 '30pm',
 '30pp',
 '30s',
 '30th',
 '31',
 '3100',
 '31p',
 '32',
 '32000',
 '3230',
 '326',
 '33',
 '330',
 '350',
 '3510i',
 '3650',
 '36504',
 '3680',
 '37819',
 '38',
 '382',
 '391784',
 '3aj',
 '3d',
 '3days',
 '3g',
 '3gbp',
 '3hrs',
 '3lions',
 '3lp',
 '3miles',
 '3mins',
 '3qxj9',
 '3rd',
 '3ss',
 '3uz',
 '3wks',
 '3x',
 '3xx',
 '40',
 '400',
 '400mins',
 '400thousad',
 '402',
 '40gb',
 '41685',
 '41782',
 '4217',
 '42478',
 '42810',
 '434',
 '440',
 '4403ldnw1a7rw18',
 '44345',
 '447797706009',
 '447801259231',
 '448712404000',
 '449050000301',
 '45',
 '450p',
 '450ppw',
 '450pw',
 '45239',
 '45pm',
 '47',
 '4742',
 '47per',
 '48',
 '4882',
 '48922',
 '49557',
 '4a',
 '4d',
 '4eva',
 '4few',
 '4fil',
 '4get',
 '4give',
 '4goten',
 '4info',
 '4jx',
 '4msgs',
 '4mths',
 '4my',
 '4qf2',
 '4t',
 '4th',
 '4the',
 '4thnov',
 '4txt',
 '4u',
 '4utxt',
 '4w',
 '4wrd',
 '4xx26',
 '4years',
 '50',
 '500',
 '5000',
 '505060',
 '50award',
 '50ea',
 '50gbp',
 '50p',
 '50perweeksub',
 '50perwksub',
 '50pm',
 '50ppm',
 '50rcvd',
 '50s',
 '5249',
 '526',
 '530',
 '54',
 '542',
 '5free',
 '5ish',
 '5k',
 '5min',
 '5mls',
 '5p',
 '5pm',
 '5th',
 '5wb',
 '5we',
 '5wkg',
 '5wq',
 '5years',
 '60',
 '600',
 '6031',
 '6089',
 '60p',
 '61',
 '61200',
 '61610',
 '62220cncl',
 '6230',
 '62468',
 '630',
 '645',
 '65',
 '650',
 '66',
 '674',
 '67441233',
 '69101',
 '69669',
 '69696',
 '69698',
 '69866',
 '69876',
 '69888',
 '69888nyt',
 '69911',
 '69969',
 '6days',
 '6hrs',
 '6missed',
 '6months',
 '6ph',
 '6pm',
 '6th',
 '6times',
 '6zf',
 '700',
 '7250',
 '7250i',
 '730',
 '731',
 '74355',
 '75',
 '750',
 '75max',
 '7634',
 '7684',
 '77',
 '78',
 '786',
 '7876150ppm',
 '7am',
 '7cfca1a',
 '7ish',
 '7mp',
 '7oz',
 '7pm',
 '7th',
 '7ws',
 '7zs',
 '800',
 '8000930705',
 '80062',
 '8007',
 '80082',
 '80086',
 '80122300p',
 '80155',
 '80160',
 '80182',
 '8027',
 '80488',
 '80608',
 '8077',
 '80878',
 '81010',
 '81151',
 '81303',
 '81618',
 '82050',
 '82242',
 '82277',
 '82324',
 '82468',
 '83021',
 '83049',
 '83110',
 '83118',
 '83222',
 '83332',
 '83355',
 '83383',
 '83435',
 '83600',
 '83738',
 '84',
 '84025',
 '84122',
 '84128',
 '84199',
 '84484',
 '85',
 '850',
 '85023',
 '85069',
 '85222',
 '8552',
 '86021',
 '861',
 '864233',
 '86688',
 '86888',
 '87021',
 '87066',
 '87070',
 '87077',
 '87121',
 '87131',
 '8714714',
 '872',
 '87239',
 '87575',
 '8800',
 '88039',
 '88066',
 '88088',
 '88222',
 '88600',
 '8883',
 '89070',
 '89080',
 '89105',
 '89545',
 '89555',
 '89693',
 '89938',
 '8lb',
 '8p',
 '8pm',
 '8th',
 '8wp',
 '900',
 '9061100010',
 '910',
 '9280114',
 '92h',
 '930',
 '945',
 '946',
 '95',
 '9755',
 '9758',
 '97n7qp',
 '98321561',
 '99',
 '9996',
 '9ae',
 '9am',
 '9ja',
 '9pm',
 '9t',
 '9yt',
 '____',
 'a21',
 'a30',
 'aa',
 'aah',
 'aaniye',
 'aaooooright',
 'aathi',
 'ab',
 'abdomen',
 'abel',
 'aberdeen',
 'abi',
 'ability',
 'abiola',
 'abj',
 'able',
 'abnormally',
 'about',
 'aboutas',
 'above',
 'absence',
 'absolutely',
 'absolutly',
 'abstract',
 'abt',
 'abta',
 'aburo',
 'ac',
 'academic',
 'acc',
 'accent',
 'accenture',
 'accept',
 'access',
 'accessible',
 'accident',
 'accidentally',
 'accommodation',
 'accomodations',
 'accordin',
 'accordingly',
 'account',
 'accounting',
 'accounts',
 'accumulation',
 'achan',
 'ache',
 'achieve',
 'acid',
 'acknowledgement',
 'acl03530150pm',
 'acnt',
 'aco',
 'across',
 'act',
 'acted',
 'actin',
 'acting',
 'action',
 'activ8',
 'activate',
 'active',
 'activities',
 'actor',
 'actual',
 'actually',
 'ad',
 'adam',
 'add',
 'addamsfa',
 'added',
 'addicted',
 'addie',
 'adding',
 'address',
 'adds',
 'adi',
 'adjustable',
 'admin',
 'admirer',
 'admission',
 'admit',
 'adore',
 'adoring',
 'adp',
 'adress',
 'adrian',
 'adrink',
 'ads',
 'adsense',
 'adult',
 'adults',
 'advance',
 'adventure',
 'adventuring',
 'advice',
 'advise',
 'advising',
 'advisors',
 'aeronautics',
 'aeroplane',
 'afew',
 'affair',
 'affairs',
 'affection',
 'affectionate',
 'affections',
 'afford',
 'afraid',
 'africa',
 'african',
 'aft',
 'after',
 'afternon',
 'afternoon',
 'afternoons',
 'aftr',
 'ag',
 'again',
 'against',
 'agalla',
 'age',
 'age16',
 'age23',
 'agency',
 'agents',
 'ages',
 'agidhane',
 'aging',
 'ago',
 'agree',
 'ah',
 'aha',
 'ahead',
 'ahhh',
 'ahmad',
 'ahold',
 'aid',
 'aids',
 'aig',
 'aight',
 'ain',
 'aint',
 'air',
 'air1',
 'airport',
 'airtel',
 'aiya',
 'aiyah',
 'aiyar',
 'aiyo',
 'ajith',
 'aka',
 'akon',
 'al',
 'alaikkum',
 'alaipayuthe',
 'albi',
 'album',
 'alcohol',
 'aldrine',
 'alert',
 'aletter',
 'alex',
 'alfie',
 'algarve',
 'algebra',
 'algorithms',
 'alian',
 'alibi',
 'alive',
 'all',
 'allah',
 'allday',
 'allo',
 'allow',
 'allowed',
 'allows',
 'almost',
 'alone',
 'along',
 'alot',
 'already',
 'alright',
 'alrite',
 'also',
 'alter',
 'alternative',
 'although',
 'alto18',
 'aluable',
 'alwa',
 'always',
 'alwys',
 'am',
 'amanda',
 'amazing',
 'ambitious',
 'ambrith',
 'ami',
 'amigos',
 'amla',
 'amma',
 'ammae',
 'amnow',
 'among',
 'amongst',
 'amore',
 'amount',
 'amp',
 'amplikater',
 'amrita',
 'ams',
 'amt',
 'amused',
 'amy',
 'an',
 'ana',
 'anal',
 'anand',
 'and',
 'anderson',
 'andre',
 'andres',
 'andrews',
 'andros',
 'angels',
 'angry',
 'animal',
 'animation',
 'anna',
 'anniversary',
 'annoncement',
 'announcement',
 'annoyin',
 'annoying',
 'anot',
 'another',
 'ans',
 'ansr',
 'answer',
 'answered',
 'answerin',
 'answering',
 'answers',
 'answr',
 'antelope',
 'antha',
 'anthony',
 'anti',
 'antibiotic',
 'any',
 'anybody',
 'anyhow',
 'anymore',
 'anyone',
 'anyones',
 'anyplaces',
 'anythiing',
 'anythin',
 'anything',
 'anythingtomorrow',
 'anytime',
 'anyway',
 'anyways',
 'anywhere',
 'aom',
 'apart',
 'apartment',
 'apes',
 'aphex',
 'apnt',
 'apo',
 'apologetic',
 'apologise',
 'apologize',
 'app',
 'apparently',
 'appeal',
 'appear',
 'appendix',
 'applausestore',
 'applebees',
 'apples',
 'application',
 'apply',
 'applyed',
 'applying',
 'appointment',
 'appointments',
 'appreciate',
 'appreciated',
 'approaching',
 'appropriate',
 'approve',
 'approved',
 'approx',
 'apps',
 'appt',
 'april',
 'aproach',
 'apt',
 'aptitude',
 'ar',
 'arab',
 'arabian',
 'arcade',
 ...]

In [14]:
pd.DataFrame(x_train_counter.toarray(), columns= cv.get_feature_names())

C:\Users\palla\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,0125698789,02,...,zealand,zed,zeros,zhong,zoe,zogtorius,zouk,èn,ú1,〨ud
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4174,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4175,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4176,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4177,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4178,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
x_train_counter.shape

(4179, 7526)

In [16]:
model=MultinomialNB()

In [17]:
model.fit(x_train_counter, y_train)

MultinomialNB()

In [19]:
model.score(cv.transform(x_test),y_test)

0.9870782483847811

In [20]:
# predictions 

emails=['Can we get together to watch football game tommorow?',
        'upto 20% discount on parking, exclusive offer just for you']

In [21]:
email_counter = cv.transform(emails)
model.predict(email_counter)

array([0, 1], dtype=int64)

In [22]:
from sklearn.pipeline import Pipeline

In [23]:
p= Pipeline([ ('v', CountVectorizer()),('mnb', MultinomialNB())])  #  multinominal use chynnath integer values use chynn

In [24]:
p.fit(x_train,y_train)
p.predict(x_test)

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [ ]:
# piplne -- nml ormich countvectorizerum multinominal um chythind
# rand function or list ayi pass chyth rand operation or operationil chynn